feat: custom keybindings support
savedra1/clipse pull request #136
Opened 2024-09-15 17:28 UTC by TiagoRibeiro25

Added functionality to allow users to define custom keybindings.

With this update, the configuration file now includes a "keybindings" section containing the default keybindings for the application. Users can modify these keybindings according to their preferences.

2024-09-15 18:05 UTC, savedra1 requested changes
Hi @TiagoRibeiro25 thank you so much for this! It's super appreciated :blue_heart: I have tested this locally and it works well. My notes are only for minor things, let me know what you think :smile:

2024-09-15 18:05 UTC, savedra1 commented on config/constants.go
> +			"fuzzySelect":   "F",
fuzzySelect - again not sure what this is. maybe I'm forgetting my own code :laughing:

2024-09-15 18:05 UTC, savedra1 commented on config/constants.go
> +		MaxHistory:      1000,
I think default limit should be kept to 100, as having a large history can cause performance issues for some machines.

2024-09-15 18:05 UTC, savedra1 commented on config/constants.go
> +		AllowDuplicates: true,
I think this should default to false.

2024-09-15 18:11 UTC, savedra1 commented on config/constants.go
> +		HistoryFilePath: "clipboard_history.json",
I would prefer to keep the values used in `defaultConfig` to the constant values that are defined above. Perhaps `defaultKeyBindings` could be added as a new const instead?

2024-09-15 18:22 UTC, savedra1 commented
> I forgot to change back to the defaults after I did some testing, sorry for that silly mistake 😋
> 
> About the fuzzySelect, I didn't look into it, but it was in the original code.

No worries! 

I think `fuzzySelect` is my bad.. not actually being used by anything. It can be dropped entirely from the `keys.go` file and from the new struct :smile:

2024-09-15 18:47 UTC, savedra1 commented
Another thought @TiagoRibeiro25, do you think it would also be a good idea to apply the custom keybinds to the secondary view screens as well? E.g the confirmation screen/preview screen. All could be handled from the same `keys.go` file.

2024-09-15 19:35 UTC, TiagoRibeiro25 commented
@savedra1 I overlooked the secondary views initially, but I've now added support for them. I had to adjust some keybindings to better suit the new setup. Another solution would be adding more specific keybindings to the config file just for those screens.

2024-09-16 15:20 UTC, savedra1 approved these changes

2024-09-16 15:21 UTC, savedra1 commented
Closes #135

2024-09-16 15:22 UTC, merged